 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author osval
 */
import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        this.setLayout(new GridBagLayout());
        this.setLocationRelativeTo(null);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        btnReparacion = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnPersonalizar = new javax.swing.JButton();
        btnPrecios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMantenimiento = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(626, 626));

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReparacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReparacion.setText("Reparacion");
        btnReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReparacionActionPerformed(evt);
            }
        });
        panelFondo.add(btnReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 187, 402, -1));

        btnLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        panelFondo.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 89, 402, -1));

        btnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        panelFondo.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 138, 402, -1));

        btnPersonalizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPersonalizar.setText("Personalizar");
        panelFondo.add(btnPersonalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 285, 402, -1));

        btnPrecios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPrecios.setText("Precios");
        panelFondo.add(btnPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 334, 402, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 67));
        jLabel2.setText("Menu de inicio");
        panelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 14, -1, -1));

        btnMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMantenimiento.setText("Mantenimiento");
        panelFondo.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 236, 402, -1));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelFondo.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 383, 402, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        FrmRegistro frm = new FrmRegistro(); 
        frm.setVisible(true);                
        dispose();        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReparacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         dispose();  
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        FrmLista frm = new FrmLista();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try{
            UIManager.setLookAndFeel(new FlatDarkPurpleIJTheme());
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
            
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnPersonalizar;
    private javax.swing.JButton btnPrecios;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReparacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
